# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy for dev

on:
    push:
        branches:
            - 'dev' # 只针对 dev 分支
        paths:
            - '.github/workflows/*'
            # - '__test__/**' # dev 不需要立即测试
            - 'src/**'
            - 'Dockerfile'
            - 'docker-compose.yml'
            - 'bin/*'

jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa # secret 在这里配置 https://github.com/shuihang/wang-ce-server.git
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "39.100.76.235" >> ~/.ssh/known_hosts
            - name: deploy # 部署
              run: |
                  ssh root@39.100.76.235 "
                    # 【注意】用 root 账号登录，手动创建 /home/xiejie/wang-ce/wang-ce-server 目录
                    # 然后 git clone https://github.com/shuihang/wang-ce-server.git -b dev （私有仓库，使用 github 用户名和密码）
                    # 记得删除 origin ，否则会暴露 github 密码

                    cd /home/xiejie/wang-ce/wang-ce-server
                    git remote add origin https://shuihang:${{secrets.WFP_PASSWORD}}@github.com/shuihang/wang-ce-server.git
                    git checkout dev
                      # 重新下载最新代码
                    git pull origin dev
                      # 删除 origin ，否则会暴露 github 密码
                    git remote remove origin
                      # 启动 docker
                      # 和 docker-compose.yml service 名字一致
                    docker-compose build test-server
                    docker-compose up -d
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa
